version: '3.8'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./etc/nginx:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs/nginx:/var/log/nginx
        links:
            - php
            - django

    php:
        build: ./images/php
        volumes:
            - ./www:/var/www

    django:
        build: ./images/django-docker
        volumes:
            - ./images/django-docker:/app
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
